---
styleguide: sourcelevel/linters
engines:
  fixme:
    enabled: true
    channel: latest
  radon:
    enabled: true
    channel: latest
    config:
      python_version: 2
  bandit:
    enabled: true
    channel: latest
    config:
      python_version: '2'
  pep8:
    enabled: true
    channel: latest
exclude_paths: []
